#Config Version, don't change it!
config-version: 7

title: SkyBlockUI
exit-button: §l§cExit
content: Manage easily your island!
create-content: Choose a preset to use to create your SkyBlock Isle.

#Options
enable-friends: true
allow-generators: true
allow-visit: true
default-generator: op

#Main form config
create-island: Create an island
join-island: Join your island
see-category: See your category
see-blocks: See blocks placed
disband-island: Disband your island
transfer: Transfer your isle
lock-unlock: Lock or Unlock your isle
visit: Visit an island
friends: SkyBlock Friends

#Create form config
basic: Basic
lost: Lost
op: OP
palm: Palm
shelly: Shelly

#Visit form config
visit-content: Visit a Player or a Friend's isle if his isle is unlocked.

#Transfer form config
transfer-content: Transfer your isle to another player or to your best friend!

#Friends main form config
friends-content: You can play SkyBlock with your friends!
invite-button: Invite a Player
accept-button: Accept an Invite
deny-button: Deny an Invite
leave-button: Leave an Isle
cooperate-button: Cooperate with a Player

#Friends invite form config
invite-content: Invite a Player or a Friend in your isle. But him needs to have disbanded the isle

#Friends cooperate form config
cooperate-content: Let a Player cooperate in your isle. Use this form to don't let a Player cooperate.
